name: Compile Check

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Objective-C compiler
      run: brew install llvm

    - name: Install OpenGL
      run: brew install mesa

    - name: Copy OpenGL directory
      run: |
        sudo mkdir -p /usr/local/include/OpenGL
        sudo cp -R /usr/local/Cellar/mesa/22.3.6_1/include/GLES3 /usr/local/include/OpenGL


    - name: Compile all .c files
      run: make
