name: Compile Check

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        brew install gcc

    - name: Install Objective-C compiler
      run: brew install llvm

    - name: Install OpenGL
      run: brew install mesa

    - name: Find OpenGL header file
      run: find /usr -name gl3.h

    - name: Create symbolic link for OpenGL
      run: |
        GL3_PATH=$(find /usr -name gl3.h)
        sudo mkdir -p /usr/local/include/OpenGL
        sudo ln -s $GL3_PATH /usr/local/include/OpenGL/gl3.h

    - name: Compile
      run: make
