name: Memory Leak Check

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y gcc valgrind

    - name: Compile all .c files except those in minilibx and specific file
      run: make

    - name: Check for memory leaks
      run: valgrind --leak-check=full --error-exitcode=1 ./miniRT
